### ISSUE TITLE
Direct view results

### ISSUE THREAD

**Issue by HanMar2021** [themetalfleece/tennis-score#4]
Hi there,

first of all i´d like to thank you for your excellent work until now. thanks! I tested your application and it would be very helpful if there would be a chance if we can show the standings of an room direct within a iframe window (f.e. direct integration in an website).

So i tried to experiment with different tags such as the room number in the url syntax (index.php?room=1&....) but i had no success. Please can you provide some extra information and help me creating a direct view of the results???

Thanks in advance!

**Comment by themetalfleece** [comment]
@HanMar2021 hey there!
Thanks for your kind words. I just pushed some code which implements the described behavior, so if you access the page with `?room=0`, it will join room `0` etc
Let me know if it works as intended!

**Comment by HanMar2021** [comment]
Thanks. Works like a charme!!!
